In [1]:
import numpy as np
import pandas as pd

In [2]:
pd.options.display.float_format = '{:.2f}'.format

In [17]:
np.set_printoptions(precision=1)

In [18]:
x1 = np.random.rand(2,5) * 10
x1

array([[8.9, 8.9, 3.6, 6. , 2. ],
       [1.4, 9.2, 5.1, 3.4, 2.5]])

In [13]:
x2 = np.random.rand(2,5) * -100
x2

array([[-85.4625931 , -50.73148865, -66.76112769, -95.83178491,
        -58.24467264],
       [ -1.46113366, -84.10393008, -80.80189922, -65.22510259,
        -25.27693001]])

In [19]:
np.concatenate([x1,x2])

array([[  8.9,   8.9,   3.6,   6. ,   2. ],
       [  1.4,   9.2,   5.1,   3.4,   2.5],
       [-85.5, -50.7, -66.8, -95.8, -58.2],
       [ -1.5, -84.1, -80.8, -65.2, -25.3]])

In [20]:
np.concatenate([x1,x2]).shape

(4, 5)

In [22]:
np.concatenate([x1,x2], axis =1)

array([[  8.9,   8.9,   3.6,   6. ,   2. , -85.5, -50.7, -66.8, -95.8,
        -58.2],
       [  1.4,   9.2,   5.1,   3.4,   2.5,  -1.5, -84.1, -80.8, -65.2,
        -25.3]])

### pd.series te sirve para crear una serie con indices de elementos np.array, te solicita desde que fila del arreglo hace la lista

In [29]:
s1 = pd.Series(x1[0], index = ['a','b','c','d','e'])

In [30]:
s1

a   8.91
b   8.89
c   3.62
d   6.03
e   2.04
dtype: float64

In [31]:
s2 = pd.Series(x2[0], index = ['c','d','e','f','g'])
s2

c   -85.46
d   -50.73
e   -66.76
f   -95.83
g   -58.24
dtype: float64

### La concatenacion de las series de pandas se concatenan a lo largo de la columna

In [34]:
pd.concat([s1,s2], axis =1)

0      1
a 8.91    nan
b 8.89    nan
c 3.62 -85.46
d 6.03 -50.73
e 2.04 -66.76
f  nan -95.83
g  nan -58.24

### Se concatenan respetando los indices repetidos, alineandolos segun el indice

In [36]:
s1.reset_index(drop=True)

0   8.91
1   8.89
2   3.62
3   6.03
4   2.04
dtype: float64

### Así se borran los indices y lo elimina de tipo columna

In [39]:
pd.concat([s1.reset_index(drop=True),s2.reset_index(drop= True)], axis = 1)

0      1
0 8.91 -85.46
1 8.89 -50.73
2 3.62 -66.76
3 6.03 -95.83
4 2.04 -58.24

In [41]:
df1 = pd.DataFrame(np.random.rand(3,2)*10,columns= ['a','b'])

In [42]:
df1

a    b
0 2.49 8.34
1 8.95 2.30
2 2.25 2.44

In [44]:
df2 = pd.DataFrame(np.random.rand(3,2)*-1,columns= ['a','b'], index=[2,3,4])
df2

a     b
2 -0.79 -0.70
3 -0.96 -0.07
4 -0.34 -0.38

In [45]:
pd.concat([df1,df2])

a     b
0  2.49  8.34
1  8.95  2.30
2  2.25  2.44
2 -0.79 -0.70
3 -0.96 -0.07
4 -0.34 -0.38

In [46]:
pd.concat([df1,df2], axis = 1)

a    b     a     b
0 2.49 8.34   nan   nan
1 8.95 2.30   nan   nan
2 2.25 2.44 -0.79 -0.70
3  nan  nan -0.96 -0.07
4  nan  nan -0.34 -0.38

### Obterner la fila que comparte datos entre los dos data frames

In [47]:
pd.concat([df1,df2], axis = 1, join='inner')

a    b     a     b
2 2.25 2.44 -0.79 -0.70

In [48]:
pd.concat([df1.reset_index(drop=True),df2.reset_index(drop=True)], axis = 1, )

a    b     a     b
0 2.49 8.34 -0.79 -0.70
1 8.95 2.30 -0.96 -0.07
2 2.25 2.44 -0.34 -0.38

### La transpuesas

In [49]:
df1.append(df2).append(df2)

a     b
0  2.49  8.34
1  8.95  2.30
2  2.25  2.44
2 -0.79 -0.70
3 -0.96 -0.07
4 -0.34 -0.38
2 -0.79 -0.70
3 -0.96 -0.07
4 -0.34 -0.38

### Hacer una append a lo largo del eje de las columnas

In [50]:
df1.T

0    1    2
a 2.49 8.95 2.25
b 8.34 2.30 2.44

In [52]:
df1.T.append(df2.T).T

a    b     a     b
0 2.49 8.34   nan   nan
1 8.95 2.30   nan   nan
2 2.25 2.44 -0.79 -0.70
3  nan  nan -0.96 -0.07
4  nan  nan -0.34 -0.38